### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by ThatIsAPseudo** [Rigellute/homebrew-tap#1]
Upgrading brew packages leads to this error :
```
$ brew upgrade
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the rigellute/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/rigellute/homebrew-tap/Formula/spotify-tui.rb:6
```

**Comment by Rigellute** [comment]
Thanks to @jottr for fixing this. I hadn't been keeping this tap up-to-date as spotify-tui is now in homebrew core.

But on the next release, I will update it.

**Comment by jottr** [comment]
I wasn't aware that `spotify-tui` is part of homebrew. Good to know.
